name: Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Release version

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'

      - name: Update Core plugin.json Version
        uses: jossef/action-set-json-field@v2.1
        with:
          file: ./genesis-core/plugin.json
          field: version
          value: ${{ github.event.inputs.version }}

      - name: Update Common plugin.json Version
        uses: jossef/action-set-json-field@v2.1
        with:
          file: ./genesis-common/plugin.json
          field: version
          value: ${{ github.event.inputs.version }}

      - name: Build Artifact
        run: ./gradlew jar

      - name: Get artifact path
        run: |
          echo "GENESIS_CORE_ARTIFACT_PATH=$(./gradlew :genesis-core:getArtifactPath -q)" >> $GITHUB_ENV
          echo "GENESIS_COMMON_ARTIFACT_PATH=$(./gradlew :genesis-common:getArtifactPath -q)" >> $GITHUB_ENV

      - name: Publish
        run: |
          ./gradlew publish \
          -PreposiliteUsername=${{ secrets.MAVEN_NAME }} \
          -PreposilitePassword=${{ secrets.MAVEN_SECRET }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          tag_name: v${{ github.event.inputs.version }}
          body: |
            Version ${{ github.event.inputs.version }}
          files: |
            ${{ env.GENESIS_CORE_ARTIFACT_PATH }}
            ${{ env.GENESIS_COMMON_ARTIFACT_PATH }}

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Increment versions"